#!/bin/sh
python manage_recette.py https://www.hellofresh.fr/recipes/le-vege-salade-de-nouilles-sauce-satay-and-eminces-vegetariens-67d99afd859430068bc53162 salade_nouilles
python manage_recette.py https://www.hellofresh.fr/recipes/miso-ramen-express-au-porc-and-soja-66cdd51c6041110ff0a4c647 ramen_porc
